name: Debricked scan & import into SSC

on: [push]

jobs:
  vulnerabilities-scan-production:
    runs-on: ubuntu-latest

    container:
      image: debricked/cli:latest-resolution-debian

    steps:
    # Running the Debricked scan
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Debricked Scan
        run: |
          debricked callgraph
          debricked scan
        env:
          DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}

    # Importing the scan results into SSC
      - name: Install fcli and log in
        run: |
          curl -L https://github.com/fortify/fcli/releases/download/v2.3.0/fcli-linux.tgz | tar -xz fcli
          ./fcli ssc session login
        env:
          FCLI_DEFAULT_SSC_USER: ${{ secrets.FCLI_DEFAULT_SSC_USER }}
          FCLI_DEFAULT_SSC_PASSWORD: ${{ secrets.FCLI_DEFAULT_SSC_PASSWORD }}
          FCLI_DEFAULT_SSC_CI_TOKEN: ${{ secrets.FCLI_DEFAULT_SSC_CI_TOKEN }}
          FCLI_DEFAULT_SSC_URL: ${{ secrets.FCLI_DEFAULT_SSC_URL }}

      - name: Import Debricked results into SSC
        run: |
          ./fcli ssc artifact import-debricked --appversion=NewDebrickedImport:1.0.0 --repository=${{ github.repository }} --branch=${{ github.head_ref || github.ref_name }} -t=${{ secrets.DEBRICKED_TOKEN }}
          
