name: Debricked scan & import into SSC

on: [push]

jobs:
  vulnerabilities-scan-production:
    runs-on: ubuntu-latest

    container:
      image: debricked/cli:latest-resolution-debian

    steps:
      - name: Install fcli
        run: |
          curl -L https://github.com/fortify/fcli/releases/download/v2.3.0/fcli-linux.tgz | tar -xz fcli
          ./fcli --version
          ./fcli ssc session login

      - name: Import Debricked results into SSC
        run: |
          ./fcli ssc artifact import-debricked --appversion=NewDebrickedImport:1.0.0 --repository=${{ github.repository }} --branch=${{ github.head_ref || github.ref_name }} -t=${{ secrets.DEBRICKED_TOKEN }}
          
      - name: Run Debricked Scan
        run: |
          debricked files find
          debricked scan
        env:
          DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}


