name: Debricked scan & import into SSC

on: [push]

jobs:
  vulnerabilities-scan-production:
    runs-on: ubuntu-latest

    container:
      image: debricked/cli:latest-resolution-debian

    steps:
    # Running the Debricked scan
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Debricked Scan
        run: |
          debricked scan
        env:
          DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}

    # Importing the scan results into SSC
      - name: Install fcli and log in
        if: success() || failure()
        run: |
          curl -L https://github.com/fortify/fcli/releases/download/v2.3.0/fcli-linux.tgz | tar -xz fcli
          ./fcli ssc session login
        env:
          FCLI_DEFAULT_SSC_CI_TOKEN: ${{ secrets.FCLI_DEFAULT_SSC_CI_TOKEN }}
          FCLI_DEFAULT_SSC_URL: ${{ secrets.FCLI_DEFAULT_SSC_URL }}

      - name: Import Debricked results into SSC
        if: success() || failure()
        run: |
          ./fcli ssc artifact import-debricked
        env:
          FCLI_DEFAULT_SSC_APPVERSION: 'NewDebrickedImport:1.0.0'
          FCLI_DEFAULT_SSC_REPOSITORY: ${{ github.repository }}
          FCLI_DEFAULT_SSC_BRANCH: ${{ github.head_ref || github.ref_name }}
          FCLI_DEFAULT_SSC_ACCESSTOKEN: ${{ secrets.DEBRICKED_TOKEN }}
