name: Debricked scan & import into SSC

on: [push]

jobs:
  vulnerabilities-scan-production:
    runs-on: ubuntu-latest

    container:
      image: debricked/cli:latest-resolution-debian

    steps:
      - name: Install fcli
        run: |
          curl -L https://github.com/fortify/fcli/releases/2.3.0/download/fcli-linux.tgz | file fcli-linux.tgz | tar -xz fcli
          ./fcli --version
          
      - name: Run Debricked Scan
        run: |
          debricked files find
          debricked scan
        env:
          DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}


